# Generated by Django 6.1 on 2026-08-31 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_medication_preferred_supplier'),
        ('orders', '0004_purchaseorderitem_expiry_date'),
        ('suppliers', '0002_remove_supplier_unique_supplier_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expiry_date', models.DateField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['expiry_date', 'received_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='purchaseorder',
            name='unique_po_number',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.medication'),
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='purchase_order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='batch', to='orders.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='medicationbatch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medication_batches', to='suppliers.supplier'),
        ),
    ]
