# Generated by Django 6.1 on 2026-08-31 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('orders', '0005_medicationbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItemBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='sale',
            name='unique_invoice',
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_id',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='saleitembatch',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='orders.medicationbatch'),
        ),
        migrations.AddField(
            model_name='saleitembatch',
            name='sale_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_allocations', to='billing.saleitem'),
        ),
    ]
