# Generated by Django 6.1 on 2026-08-31 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_saleitembatch_remove_sale_unique_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitembatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 8, 31, 13, 16, 14, 492021, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
