# Generated by Django 6.1 on 2026-08-31 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_saleitembatch_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='copay',
        ),
    ]
