# Generated by Django 6.1 on 2026-08-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('generic_name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=50)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('ndc', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=80)),
                ('form_type', models.CharField(choices=[('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Liquid', 'Liquid'), ('Injection', 'Injection')], max_length=20)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('shelf_location', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(max_length=150)),
                ('expiry_date', models.DateField()),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preferred_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('sku',), name='unique_medication_sku')],
            },
        ),
    ]
