# Generated by Django 6.1 on 2026-08-31 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='expiry_date',
        ),
    ]
