# Generated by Django 6.1 on 2026-08-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_medication_cost_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='preferred_supplier',
        ),
    ]
