# Generated by Django 6.1 on 2026-08-28 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='MedVault Main Dispensary', max_length=150)),
                ('timezone', models.CharField(default='Eastern Standard Time (EST / GMT-5)', max_length=100)),
                ('license_number', models.CharField(default='', max_length=100)),
                ('currency', models.CharField(default='USD ($) - US Dollars', max_length=80)),
                ('phone', models.CharField(default='', max_length=30)),
                ('address', models.CharField(default='', max_length=255)),
                ('low_stock_threshold', models.PositiveIntegerField(default=30)),
                ('auto_reorder', models.BooleanField(default=True)),
                ('critical_low_alert', models.BooleanField(default=True)),
                ('batch_expiry_warning', models.BooleanField(default=True)),
                ('daily_sales_pdf', models.BooleanField(default=False)),
                ('store_info', models.JSONField(blank=True, default=dict)),
                ('tax_pricing', models.JSONField(blank=True, default=dict)),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('backup_data', models.JSONField(blank=True, default=dict)),
                ('security', models.JSONField(blank=True, default=dict)),
                ('integrations', models.JSONField(blank=True, default=dict)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
