# Generated by Django 6.1 on 2026-08-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('representative_name', models.CharField(max_length=150)),
                ('representative_role', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('payment_terms', models.CharField(max_length=80)),
                ('lead_time', models.CharField(max_length=80)),
                ('tier', models.CharField(choices=[('TIER-1 PREFERRED', 'TIER-1 PREFERRED'), ('TIER-2 STANDARD', 'TIER-2 STANDARD'), ('TIER-3 BACKUP', 'TIER-3 BACKUP')], default='TIER-2 STANDARD', max_length=30)),
                ('rating', models.PositiveSmallIntegerField(default=0)),
                ('last_shipment_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_supplier_name')],
            },
        ),
    ]
