# Generated by Django 6.1 on 2026-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='supplier',
            name='unique_supplier_name',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
